// 1AM-67 / 1AM-79: Congress directory helpers
//
// Single import surface for working with the Congress member directory.
// Source: src/data/congress.json (generated by scripts/fetch-congress.mjs).
//
// All members are pre-sorted by lastName then firstName (deterministic order
// from the fetch script). Helpers preserve order unless explicitly noted.
//
// USAGE:
//   import {
//     MEMBERS,
//     findByBioguide,
//     findByName,
//     filterByChamber,
//     filterByParty,
//     filterByState,
//     applyFilters,
//     getSuggested,
//   } from './lib/congress';

import congressData from '../data/congress.json' with { type: 'json' };

/** @typedef {import('../data/schema.js').Member} Member */

// ── Full directory ──────────────────────────────────────────────────────────
/**
 * All current Congress members, sorted by lastName then firstName.
 * Frozen to prevent accidental mutation by callers.
 * @type {ReadonlyArray<Member>}
 */
export const MEMBERS = Object.freeze(congressData);

// ── Suggested members for onboarding ────────────────────────────────────────
// Hand-picked 8 high-profile members for the "Suggested to follow" section
// in the onboarding picker. Mix across party (D/R/I) and chamber (House/Senate)
// for visual diversity. Names are familiar to anyone who reads US politics
// headlines, lowering the barrier-to-pick during onboarding.
//
// Update criteria when picking: high media presence, varied geography, mix of
// parties + chambers. Avoid making it look like a partisan-curated list.
const SUGGESTED_BIOGUIDE_IDS = Object.freeze([
  'P000197', // Nancy Pelosi (D-CA, House) — ex-Speaker, frequent trade headlines
  'M000355', // Mitch McConnell (R-KY, Senate) — ex-Senate leader
  'S000148', // Charles Schumer (D-NY, Senate) — Senate Majority Leader
  'S000033', // Bernard Sanders (I-VT, Senate) — high media visibility
  'T000278', // Tommy Tuberville (R-AL, Senate) — frequent trade headlines
  'C001120', // Dan Crenshaw (R-TX, House) — high media visibility
  'O000172', // Alexandria Ocasio-Cortez (D-NY, House) — high media visibility
  'K000389', // Ro Khanna (D-CA, House) — frequent trade headlines
]);

/**
 * The hand-picked Suggested members for onboarding, in display order.
 * Returns a new array each call. Members not found (e.g. retired) are skipped
 * silently — caller should expect length <= SUGGESTED_BIOGUIDE_IDS.length.
 * @returns {Member[]}
 */
export function getSuggested() {
  const result = [];
  for (const id of SUGGESTED_BIOGUIDE_IDS) {
    const m = findByBioguide(id);
    if (m) result.push(m);
  }
  return result;
}

// ── Lookup ──────────────────────────────────────────────────────────────────
/**
 * Find a single member by Bioguide ID. Returns null if not found.
 * @param {string} bioguideId
 * @returns {Member | null}
 */
export function findByBioguide(bioguideId) {
  if (!bioguideId) return null;
  return MEMBERS.find((m) => m.bioguideId === bioguideId) || null;
}

// ── Search ──────────────────────────────────────────────────────────────────
/**
 * Search members by free-text query. Case-insensitive, diacritic-tolerant,
 * matches against firstName, lastName, officialFull, and nickname.
 *
 * Results are ranked: exact full-name match > prefix match > substring match.
 * Within each rank, alphabetical order (lastName, firstName).
 *
 * Empty / whitespace-only query returns an empty array — call sites should
 * decide whether to show all members or a suggested set instead.
 *
 * @param {string} query
 * @param {ReadonlyArray<Member>} [members] - optional pool to search within
 * @returns {Member[]}
 */
export function findByName(query, members = MEMBERS) {
  const q = normaliseSearchString(query);
  if (!q) return [];

  const exactMatches = [];
  const prefixMatches = [];
  const substringMatches = [];

  for (const m of members) {
    const haystacks = buildHaystacks(m);

    let matched = 'none';
    for (const h of haystacks) {
      if (h === q) {
        matched = 'exact';
        break;
      }
      if (h.startsWith(q) && matched !== 'exact') {
        matched = 'prefix';
        continue;
      }
      if (h.includes(q) && matched === 'none') {
        matched = 'substring';
      }
    }

    if (matched === 'exact') exactMatches.push(m);
    else if (matched === 'prefix') prefixMatches.push(m);
    else if (matched === 'substring') substringMatches.push(m);
  }

  // exactMatches/prefixMatches/substringMatches are already in directory order
  // (which is alphabetical by lastName, firstName).
  return [...exactMatches, ...prefixMatches, ...substringMatches];
}

// ── Filters ─────────────────────────────────────────────────────────────────
/**
 * Filter members by chamber. Pass an array to filter for multiple chambers.
 * @param {'House' | 'Senate' | Array<'House' | 'Senate'>} chamber
 * @param {ReadonlyArray<Member>} [members]
 * @returns {Member[]}
 */
export function filterByChamber(chamber, members = MEMBERS) {
  if (!chamber || (Array.isArray(chamber) && chamber.length === 0)) {
    return [...members];
  }
  const allowed = Array.isArray(chamber) ? new Set(chamber) : new Set([chamber]);
  return members.filter((m) => allowed.has(m.chamber));
}

/**
 * Filter members by party. Pass an array to filter for multiple parties (OR).
 * @param {'D' | 'R' | 'I' | Array<'D' | 'R' | 'I'>} party
 * @param {ReadonlyArray<Member>} [members]
 * @returns {Member[]}
 */
export function filterByParty(party, members = MEMBERS) {
  if (!party || (Array.isArray(party) && party.length === 0)) {
    return [...members];
  }
  const allowed = Array.isArray(party) ? new Set(party) : new Set([party]);
  return members.filter((m) => allowed.has(m.party));
}

/**
 * Filter members by state (2-letter USPS code). Pass an array for multiple states.
 * @param {string | string[]} state
 * @param {ReadonlyArray<Member>} [members]
 * @returns {Member[]}
 */
export function filterByState(state, members = MEMBERS) {
  if (!state || (Array.isArray(state) && state.length === 0)) {
    return [...members];
  }
  const allowed = Array.isArray(state)
    ? new Set(state.map((s) => s.toUpperCase()))
    : new Set([state.toUpperCase()]);
  return members.filter((m) => allowed.has(m.state));
}

/**
 * Apply multiple filters + search in one call. All conditions are ANDed.
 * Empty/missing filter values are ignored (don't restrict).
 *
 * @param {Object} options
 * @param {string} [options.search]   - free-text search (see findByName)
 * @param {Array<'House'|'Senate'>} [options.chamber]
 * @param {Array<'D'|'R'|'I'>} [options.party]
 * @param {string[]} [options.state]  - 2-letter codes
 * @param {ReadonlyArray<Member>} [options.members]
 * @returns {Member[]}
 */
export function applyFilters({
  search,
  chamber,
  party,
  state,
  members = MEMBERS,
} = {}) {
  let result = members;

  if (chamber && (!Array.isArray(chamber) || chamber.length > 0)) {
    result = filterByChamber(chamber, result);
  }
  if (party && (!Array.isArray(party) || party.length > 0)) {
    result = filterByParty(party, result);
  }
  if (state && (!Array.isArray(state) || state.length > 0)) {
    result = filterByState(state, result);
  }
  // Search is applied last so it can rank within the already-filtered set
  if (search && search.trim()) {
    result = findByName(search, result);
  } else {
    result = [...result];
  }

  return result;
}

// ── Internal helpers ────────────────────────────────────────────────────────
/**
 * Lowercase + trim + diacritic strip.
 * "José" → "jose", "  Pelosi  " → "pelosi", "" → "".
 */
function normaliseSearchString(s) {
  if (!s || typeof s !== 'string') return '';
  return s
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '') // strip combining diacritics
    .toLowerCase()
    .trim();
}

/**
 * Build the lowercased + diacritic-stripped strings to search against for a member.
 * Order matters for ranking — earlier entries are weighted higher in findByName.
 */
function buildHaystacks(member) {
  const haystacks = [];
  const officialFull = normaliseSearchString(member.officialFull);
  const fullName = normaliseSearchString(`${member.firstName} ${member.lastName}`);
  const lastName = normaliseSearchString(member.lastName);
  const firstName = normaliseSearchString(member.firstName);

  if (officialFull) haystacks.push(officialFull);
  if (fullName && !haystacks.includes(fullName)) haystacks.push(fullName);
  if (lastName) haystacks.push(lastName);
  if (firstName) haystacks.push(firstName);
  if (member.nickname) {
    const nick = normaliseSearchString(member.nickname);
    if (nick) haystacks.push(nick);
  }

  return haystacks;
}
